name: Publish Docker image to GitHub Container Registry

on:
  push:
    branches:
      - Containers

env:
  IMAGE_NAME: giusek23/be-taleswaver:latest

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: 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
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}
          build-args: |
            POSTGRES_DB=taleswaver
            POSTGRES_USER=postgres
            POSTGRES_PASSWORD=password
          platforms: linux/amd64,linux/arm64
          auth:
            username: CodeNoo6
            password: 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
