name: Publish Docker Image to GitHub Packages
on:
  push:
    branches:
      - Containers
env:
  IMAGE_NAME: giusek23/be-taleswaver:latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to GitHub Packages
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: 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
        
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ env.IMAGE_NAME }}

